import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap", 
});

export const metadata = {
  title: "Hookik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${montserrat.variable} antialiased`}>{children}</body>
        <Toaster position="top-right" richColors />
      </Providers>
    </html>
  );
}
